services:
  website:
    container_name: website-dev
    build:
      context: ./next-app
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - ./next-app:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL:-}
      TERMINAL_DISCORD_WEBHOOK_URL: ${TERMINAL_DISCORD_WEBHOOK_URL:-}
      NEXT_PUBLIC_API_URL: http://localhost:4000

  api:
    container_name: api
    build: ./api
    restart: unless-stopped
    networks:
      - proxy
    environment:
      NODE_ENV: development
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL:-}
      TERMINAL_DISCORD_WEBHOOK_URL: ${TERMINAL_DISCORD_WEBHOOK_URL:-}
      SQLITE_PATH: /data/database.db
    volumes:
      - ./api:/app
      - api-node-modules:/app/node_modules
      - ./api/data:/data

networks:
  proxy:
    external: true

volumes:
  api-node-modules:
